import styles from './order-cards.module.css';
import { Order, OrderStatus } from '../../../model/order';
import OrderCard from './order-card/order-card';

const DEBUG_ORDERS: Order[] = [
	{
		ingredients: [
			{
				_id: '643d69a5c3f7b9001cfa093c',
				name: 'Краторная булка N-200i',
				type: 'bun',
				proteins: 80,
				fat: 24,
				carbohydrates: 53,
				calories: 420,
				price: 1255,
				image: 'https://code.s3.yandex.net/react/code/bun-02.png',
				image_mobile: 'https://code.s3.yandex.net/react/code/bun-02-mobile.png',
				image_large: 'https://code.s3.yandex.net/react/code/bun-02-large.png',
				__v: 0,
			},
			{
				_id: '643d69a5c3f7b9001cfa093e',
				name: 'Филе Люминесцентного тетраодонтимформа',
				type: 'main',
				proteins: 44,
				fat: 26,
				carbohydrates: 85,
				calories: 643,
				price: 988,
				image: 'https://code.s3.yandex.net/react/code/meat-03.png',
				image_mobile: 'https://code.s3.yandex.net/react/code/meat-03-mobile.png',
				image_large: 'https://code.s3.yandex.net/react/code/meat-03-large.png',
				__v: 0,
			},
			{
				_id: '643d69a5c3f7b9001cfa0942',
				name: 'Соус Spicy-X',
				type: 'sauce',
				proteins: 30,
				fat: 20,
				carbohydrates: 40,
				calories: 30,
				price: 90,
				image: 'https://code.s3.yandex.net/react/code/sauce-02.png',
				image_mobile: 'https://code.s3.yandex.net/react/code/sauce-02-mobile.png',
				image_large: 'https://code.s3.yandex.net/react/code/sauce-02-large.png',
				__v: 0,
			},
			{
				_id: '643d69a5c3f7b9001cfa0942',
				name: 'Соус Spicy-X',
				type: 'sauce',
				proteins: 30,
				fat: 20,
				carbohydrates: 40,
				calories: 30,
				price: 90,
				image: 'https://code.s3.yandex.net/react/code/sauce-02.png',
				image_mobile: 'https://code.s3.yandex.net/react/code/sauce-02-mobile.png',
				image_large: 'https://code.s3.yandex.net/react/code/sauce-02-large.png',
				__v: 0,
			},
			{
				_id: '643d69a5c3f7b9001cfa0942',
				name: 'Соус Spicy-X',
				type: 'sauce',
				proteins: 30,
				fat: 20,
				carbohydrates: 40,
				calories: 30,
				price: 90,
				image: 'https://code.s3.yandex.net/react/code/sauce-02.png',
				image_mobile: 'https://code.s3.yandex.net/react/code/sauce-02-mobile.png',
				image_large: 'https://code.s3.yandex.net/react/code/sauce-02-large.png',
				__v: 0,
			},
			{
				_id: '643d69a5c3f7b9001cfa0942',
				name: 'Соус Spicy-X',
				type: 'sauce',
				proteins: 30,
				fat: 20,
				carbohydrates: 40,
				calories: 30,
				price: 90,
				image: 'https://code.s3.yandex.net/react/code/sauce-02.png',
				image_mobile: 'https://code.s3.yandex.net/react/code/sauce-02-mobile.png',
				image_large: 'https://code.s3.yandex.net/react/code/sauce-02-large.png',
				__v: 0,
			},
			{
				_id: '643d69a5c3f7b9001cfa0942',
				name: 'Соус Spicy-X',
				type: 'sauce',
				proteins: 30,
				fat: 20,
				carbohydrates: 40,
				calories: 30,
				price: 90,
				image: 'https://code.s3.yandex.net/react/code/sauce-02.png',
				image_mobile: 'https://code.s3.yandex.net/react/code/sauce-02-mobile.png',
				image_large: 'https://code.s3.yandex.net/react/code/sauce-02-large.png',
				__v: 0,
			},
			{
				_id: '643d69a5c3f7b9001cfa0942',
				name: 'Соус Spicy-X',
				type: 'sauce',
				proteins: 30,
				fat: 20,
				carbohydrates: 40,
				calories: 30,
				price: 90,
				image: 'https://code.s3.yandex.net/react/code/sauce-02.png',
				image_mobile: 'https://code.s3.yandex.net/react/code/sauce-02-mobile.png',
				image_large: 'https://code.s3.yandex.net/react/code/sauce-02-large.png',
				__v: 0,
			},
			{
				_id: '643d69a5c3f7b9001cfa093c',
				name: 'Краторная булка N-200i',
				type: 'bun',
				proteins: 80,
				fat: 24,
				carbohydrates: 53,
				calories: 420,
				price: 1255,
				image: 'https://code.s3.yandex.net/react/code/bun-02.png',
				image_mobile: 'https://code.s3.yandex.net/react/code/bun-02-mobile.png',
				image_large: 'https://code.s3.yandex.net/react/code/bun-02-large.png',
				__v: 0,
			},
		],
		_id: '692d98d7a64177001b3217af',
		owner: {
			name: 'Olga',
			email: 'oska.salova@yandex.ru',
			createdAt: '2025-10-28T12:24:18.324Z',
			updatedAt: '2025-11-03T11:18:36.098Z',
		},
		status: OrderStatus.done,
		name: 'Краторный бургер',
		createdAt: '2025-12-01T13:32:07.554Z',
		updatedAt: '2025-12-01T13:32:07.737Z',
		number: 95829,
		price: 2510,
	},
	{
		ingredients: [
			{
				_id: '643d69a5c3f7b9001cfa093c',
				name: 'Краторная булка N-200i',
				type: 'bun',
				proteins: 80,
				fat: 24,
				carbohydrates: 53,
				calories: 420,
				price: 1255,
				image: 'https://code.s3.yandex.net/react/code/bun-02.png',
				image_mobile: 'https://code.s3.yandex.net/react/code/bun-02-mobile.png',
				image_large: 'https://code.s3.yandex.net/react/code/bun-02-large.png',
				__v: 0,
			},
			{
				_id: '643d69a5c3f7b9001cfa093e',
				name: 'Филе Люминесцентного тетраодонтимформа',
				type: 'main',
				proteins: 44,
				fat: 26,
				carbohydrates: 85,
				calories: 643,
				price: 988,
				image: 'https://code.s3.yandex.net/react/code/meat-03.png',
				image_mobile: 'https://code.s3.yandex.net/react/code/meat-03-mobile.png',
				image_large: 'https://code.s3.yandex.net/react/code/meat-03-large.png',
				__v: 0,
			},
			{
				_id: '643d69a5c3f7b9001cfa0942',
				name: 'Соус Spicy-X',
				type: 'sauce',
				proteins: 30,
				fat: 20,
				carbohydrates: 40,
				calories: 30,
				price: 90,
				image: 'https://code.s3.yandex.net/react/code/sauce-02.png',
				image_mobile: 'https://code.s3.yandex.net/react/code/sauce-02-mobile.png',
				image_large: 'https://code.s3.yandex.net/react/code/sauce-02-large.png',
				__v: 0,
			},
			{
				_id: '643d69a5c3f7b9001cfa0942',
				name: 'Соус Spicy-X',
				type: 'sauce',
				proteins: 30,
				fat: 20,
				carbohydrates: 40,
				calories: 30,
				price: 90,
				image: 'https://code.s3.yandex.net/react/code/sauce-02.png',
				image_mobile: 'https://code.s3.yandex.net/react/code/sauce-02-mobile.png',
				image_large: 'https://code.s3.yandex.net/react/code/sauce-02-large.png',
				__v: 0,
			},
			{
				_id: '643d69a5c3f7b9001cfa0942',
				name: 'Соус Spicy-X',
				type: 'sauce',
				proteins: 30,
				fat: 20,
				carbohydrates: 40,
				calories: 30,
				price: 90,
				image: 'https://code.s3.yandex.net/react/code/sauce-02.png',
				image_mobile: 'https://code.s3.yandex.net/react/code/sauce-02-mobile.png',
				image_large: 'https://code.s3.yandex.net/react/code/sauce-02-large.png',
				__v: 0,
			},
			{
				_id: '643d69a5c3f7b9001cfa0942',
				name: 'Соус Spicy-X',
				type: 'sauce',
				proteins: 30,
				fat: 20,
				carbohydrates: 40,
				calories: 30,
				price: 90,
				image: 'https://code.s3.yandex.net/react/code/sauce-02.png',
				image_mobile: 'https://code.s3.yandex.net/react/code/sauce-02-mobile.png',
				image_large: 'https://code.s3.yandex.net/react/code/sauce-02-large.png',
				__v: 0,
			},
			{
				_id: '643d69a5c3f7b9001cfa0942',
				name: 'Соус Spicy-X',
				type: 'sauce',
				proteins: 30,
				fat: 20,
				carbohydrates: 40,
				calories: 30,
				price: 90,
				image: 'https://code.s3.yandex.net/react/code/sauce-02.png',
				image_mobile: 'https://code.s3.yandex.net/react/code/sauce-02-mobile.png',
				image_large: 'https://code.s3.yandex.net/react/code/sauce-02-large.png',
				__v: 0,
			},
			{
				_id: '643d69a5c3f7b9001cfa0942',
				name: 'Соус Spicy-X',
				type: 'sauce',
				proteins: 30,
				fat: 20,
				carbohydrates: 40,
				calories: 30,
				price: 90,
				image: 'https://code.s3.yandex.net/react/code/sauce-02.png',
				image_mobile: 'https://code.s3.yandex.net/react/code/sauce-02-mobile.png',
				image_large: 'https://code.s3.yandex.net/react/code/sauce-02-large.png',
				__v: 0,
			},
			{
				_id: '643d69a5c3f7b9001cfa093c',
				name: 'Краторная булка N-200i',
				type: 'bun',
				proteins: 80,
				fat: 24,
				carbohydrates: 53,
				calories: 420,
				price: 1255,
				image: 'https://code.s3.yandex.net/react/code/bun-02.png',
				image_mobile: 'https://code.s3.yandex.net/react/code/bun-02-mobile.png',
				image_large: 'https://code.s3.yandex.net/react/code/bun-02-large.png',
				__v: 0,
			},
		],
		_id: '692d98d7a64177001b3217aa',
		owner: {
			name: 'Olga',
			email: 'oska.salova@yandex.ru',
			createdAt: '2025-10-28T12:24:18.324Z',
			updatedAt: '2025-11-03T11:18:36.098Z',
		},
		status: OrderStatus.done,
		name: 'Краторный бургер',
		createdAt: '2025-12-01T13:32:07.554Z',
		updatedAt: '2025-12-01T13:32:07.737Z',
		number: 98829,
		price: 2510,
	},
];

interface OrderCardsProps {
	isHistory: boolean;
}

function OrderCards({ isHistory }: OrderCardsProps) {
	const orders = DEBUG_ORDERS;
	const handleOrderClick = (order: Order) => {
		console.log('** Order click', order);
		// navigate(AppRoutes.OrderFeed.replace(':id', order._id), {
		// 	state: { backgroundLocation: location },
		// });
	};

	return (
		<ul className={`${styles.cards} ${isHistory ? styles.cardsLarge : styles.cardsSmall}`}>
			{orders.map(order => (
				<li key={order._id} className={styles.card}>
					<OrderCard order={order} onClick={handleOrderClick} showStatus={isHistory} />
				</li>
			))}
		</ul>
	);
}

export default OrderCards;
